const express =require("express")
const router =express.Router()
const {getGoals}=require('../controller/goalController')
const {setGoal}=require('../controller/goalController')
const {updateGoal}=require('../controller/goalController')
const {deleteGoal}=require('../controller/goalController')
const {protect}=require('../middlwware/authMiddleware')
router.route('/').get(protect,getGoals).post(protect,setGoal)
router.route('/:id').put(protect,updateGoal).delete(protect,deleteGoal)
// router.get('/',getGoals)
// router.post('/',setGoals)
// router.put('/:id',putGoals)
// router.delete('/:id',deleteGoals)
module.exports = router